### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by TekkaGB** [AnimatedSwine37/Find-a-Friend#1]
Are you sure the holiday check from lmap is correct for your use?
void check_if_holiday()
{
    // This is the logic lmap uses so it should be right
    if (DATE_CHK(4, 12) == 1 || GET_TIME_OF_DAY() == 3)
    {
        isHoliday = 1;
    }
    else
    {
        isHoliday = 0;
    }
}
Seems to only check if its 4/12 in the afternoon and no other date or time

Also found out that your Sun arcana is a bit off.  For some reason 27 and 28 is Ayane and 25 and 26 is Yumi.  25 seems to give the actual level rather than 26 though.  Perhaps that's because I didn't romance Yumi or something.

Also for your hooks you should hide the option to see it if you're tired after going to the tv world or not supposed to go out at night.  The flags I found corresponding to this for my Dojima's Coffee mod were BIT_CHK( 0 + 0x0400 + 0x0800 + 2 ) and BIT_CHK( 0 + 0x0400 + 1726 ).

So I suggest switching the if statements to if (numSelectionsRemoved == 16 || BIT_CHK( 0 + 0x0400 + 0x0800 + 2 ) || BIT_CHK( 0 + 0x0400 + 1726 ))

**Comment by AnimatedSwine37** [comment]
1. Yes, I'm pretty sure the holiday check is correct. I think the way it works is on holidays at the day time the time is displayed as "daytime" (which is time 3), whereas you get "after school" on other days (which I guess is time 4 or some other). I'm not exactly sure why it checks if it's April 12 but that's the logic lmap used to send you to the school gate instead of into school. (It's an or statement so it does check every day)
2. I didn't realise Yumi had her own social link id as I have Ayane, I guess that means I can split up her and Ayane into separate options. Also, I've been going on the assumption that the reason some have two is because one is leveled up if you romance them so I always just use whichever one is bigger.
3. Thanks for telling me about those flags, I've done what you suggested and updated the if statements so it shouldn't show on days you can't go out. ([This commit](https://github.com/AnimatedSwine37/Find-a-Friend/commit/c4dd950d995e377011bc7b659e8148ae807f4a72))

**Comment by AnimatedSwine37** [comment]
Both of the issues are now fixed with V1.3

**Comment by TekkaGB** [comment]
Thanks for the speedy fixes!  And yes the holiday does make sense to me now.  For some reason I was thinking the || was acting like an &&
