### ISSUE TITLE
Feature suggestion - Leaving home sound effect

### ISSUE THREAD

**Issue by rudiger-gh** [AnimatedSwine37/Find-a-Friend#21]
When you leave the Dojima Residence or return home either through the front door or from the "Go outside" menu option, a sliding door sound effect plays on the loading screen.

Is it possible to have this sound effect play when selecting a social link from Find a Friend that takes you to or from home?

EDIT (27.02.21):
There's also a sound effect for walking down the stairs that plays when you're at home. Could be another good one to use if you're upstairs and select Dojima or Nanako.

Thanks!

![image](https://user-images.githubusercontent.com/53123052/109181731-2aa86700-7784-11eb-99f3-0f931d727ec2.png)

**Comment by AnimatedSwine37** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Find a Friend](https://trello.com/c/bteiHjYb/1-find-a-friend)

**Comment by AnimatedSwine37** [comment]
One interesting thing that I found out whilst doing this is that there is no door sound effect when going downstairs using the vanilla "living room" option. I'm fairly sure this is unintentional as it plays one of the two sound effects that make it up (for whatever reason for the door sound effect when going downstairs it only works if you play two effects one after another with a wait otherwise you get either no noise or a tiny blip). So, I fixed this as well.
